config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'blog_post#home_page'
  get 'blog_post' => 'blog_post#index'
  get 'blog_post/:id' => 'blog_post#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_post_controller.rb
class BlogPostController < ApplicationController
    def home_page
        @home_page
    end
    
    def index
        @blog_post = BlogPost.all
    end

    def blog_title
        @blog_title = BlogPost.find(params[:id])
    end
    def show
        @at_blog = BlogPost.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_post_helper.rb
module BlogPostHelper
end

app/views/blog_post/index.html.erb
<h1> Welcome to Our Blog </h1>

<ul>
    <% @blog_post.each do |title| %>

        <li>
            <%=link_to title.title, blog_post_path(title) %>
        </li>
    <% end %>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FullStackRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>